### ISSUE TITLE
Persist monitors settings in Gome

### ISSUE THREAD

**Issue by jankaifer** [nix-community/impermanence#107]
Gnome saves monitor configuration inside `~/.config/monitors.xml`.
Even when you add this file to your config, you need to make sure to copy valid `monitors.xml` into `/persist/$HOME/.config/monitors.xml` (or where you persist your files).

It will not work without that file in persistent storage and `touch` ing it won't work (empty file).

Feel free to close this issue. I just wanted to document this somewhere.
But it would be great if we could minimize these manual interventions somehow (so that the only thing I need to add to `/persist` is my nixos config).

**Comment by talyz** [comment]
Indeed, this is by design. We can't reliably move already existent files to persistent storage for a few reasons, but mainly because they may already be in use, so this has to be a manual step. What we could do is create auto-generated cli commands to move directories and files, but it feels outside the scope of this issue.

In most cases it will work when you don't have a file in persistent storage, as then a symlink will be pointing to a non-existent file and it will then be created, but that might not be the case for `monitors.xml`.
