### ISSUE TITLE
Add `hideMounts` option to Home Manager module

### ISSUE THREAD

**Issue by Anomalocaridid** [nix-community/impermanence#127]
Currently, it does not look like the `hideMounts` option in the NixOS module applies to mounts created with the Home Manager. However, I also cannot find any equivalent option in the Home Manager module.

**Comment by nklsfrt** [comment]
Just to give you some insight on why I assume this isn't a thing yet:

As you can see [here](https://github.com/nix-community/impermanence/blob/0f317c2e9e56550ce12323eb39302d251618f5b5/nixos.nix#L60), system level mounts are generated and placed in /etc/fstab as bind mounts (via mount --bind) and supplied with the x-gvfs-hide mount option. This option is saved to user-space and informs the user interface to hide the device from all places it would show up in.

Since mounts happening in user-space lack the privileges required to execute the mount command, they make use of the FUSE implementation of bind mounts called bindfs. AFAIK this simply doesn't support the x-gvfs-hide mount option.

**Comment by Anomalocaridid** [comment]
While solving an unrelated issue<sup>[1]</sup>, I found that using the system-level NixOS module to declare user-level impermanence works as a workaround.

Closing this issue because I assume this is the best we'll get.

<sup>[1]</sup>`Too many open files` error caused by bindfs
