### ISSUE TITLE
Are files read-only?

### ISSUE THREAD

**Issue by bbigras** [nix-community/impermanence#15]
I just tried this for the first time. I had to create `/persist/etc/machine-id` but now `/etc/machine-id` points to a file in the nix store. Which I expect to be read-only. It's fine for the machine-id but it wouldn't be for network-manager stuff or logs. Which I would prefer to be writable but still persistent between reboots.

```nix
  environment.persistence."/persist" = {
    files = [
      "/etc/machine-id"
    ];
  };
```

**Comment by etu** [comment]
I would expect that your `/etc/machine-id` is a symlink chain that looks something like this:
```
/etc/machine-id -> /etc/static/machine-id -> /nix/store/hvnykaklbwa55pl8znhq7lsjf76vq6gy--persistent-etc-machine-id -> /persist/etc/machine-id
```

And since it's symlinks they don't have to be writable in the entire chain, so if you make sure the directory `/persist/etc` exists and then create the file it should be fully possible to write to `/etc/machine-id` :)

**Comment by bbigras** [comment]
> they don't have to be writable in the entire chain

Uh I didn't know that. Or forgot about it.

Thank you very much.
