### ISSUE TITLE
Best practice to split configuration

### ISSUE THREAD

**Issue by matthiasdotsh** [nix-community/impermanence#173]
I am currently in the process of converting my entire system, including my home directory, to impermanence.

I differentiate between data that I only leave locally on the system but survive a reboot (cache) and data that I also back up (safe).

Unfortunately, it is sometimes quite time-consuming to find out where programs store data (I usually solve this by taking a zfs snapshot before installing/starting the program and then looking at what data has been added by the installation).

To keep it neat and tidy, I would like to save the data in the following form in my configuration.nix:

```nix
  # Nextcloud client
  environment.persistence = {
    "/cache" = {
      users.ms = {
        directories = [
          ".config/Nextcloud"
          ".local/share/keyrings"
          ".local/share/Nextcloud"
        ];
        files =
          [ ".config/autostart/com.nextcloud.desktopclient.nextcloud.desktop" ];
      };
    };
    "/safe" = { users.ms = { directories = [ "nc-essen" ]; }; };
  };
```

This works for one application, but I don't know how to add a second one.
When I add e.g.

```nix
 # General
  environment.persistence = {
    "/cache" = {
      hideMounts = true;
      directories = [
        "/var/log"
        "/var/lib/bluetooth"
        "/var/lib/nixos"
        "/var/lib/systemd/coredump"
        "/etc/NetworkManager/system-connections"
      ];
      users.ms = { directories = [ "Downloads" ]; };
    };
};
```

I'll get an error `attribute /cache already defined at ...`

Is there any idea how I can solve this or is there another way to design the configuration so that you can see which data belongs to the respective programs?

**Comment by coritanic** [comment]
**Note:** This isn't relevant in this repository since it's a Nix thing. You should normally ask this in [NixOS Discourse's help section](https://discourse.nixos.org/c/learn/9). But since you asked:

Nix merges the same attributes when found in separate files. This isn't the case when the same attributes are found more than once in a single file (e.g. 2 `environment.persistence."/cache"` in one file).

There is no best practice for what you are asking, different people do it differently. The most straightforward way is creating different Nix files for different applications and importing them in `configuration.nix` (same way as `hardware-configuration.nix`).

If you want to keep it in one file, you would do something like this (adjust to your `configuration.nix`):
```nix
{ config, lib, ... }:
with lib;
{
  environment.persistence."/test" = mkMerge [

    {
      hideMounts = true;
      directories = [ "/testdirs/regular1" ];
    }

    { directories = [ "/testdirs/regular2" ]; }

    (mkIf config.services.nextcloud.enable { directories = [ "/testdirs/nextcloud" ]; })

  ];
}
```
