### ISSUE TITLE
Does not work with Docker

### ISSUE THREAD

**Issue by eyJhb** [nix-community/impermanence#35]
If you cd to some dir, that is managed with impermanence, and do

```
docker run --rm -it -v $(pwd):/src alpine
```

Then you will get a error like `docker: Error response from daemon: error while creating mount source path '/home/eyjhb/projects': mkdir /home/eyjhb/projects: file exists.`

This seems to be a problem with the bindfs method, as it worked just fine with symlinks (and works fine if I use the actual dir, not the one it bindfs).

**Comment by talyz** [comment]
This probably happens because fuse mounts can't be read by other users by default. You could try to fix this by setting the `programs.fuse.userAllowOther` to `true` in your NixOS configuration and removing the `--no-allow-other` flag given to `bindfs`. It would be nice to have this configurable and inform about it.

**Comment by talyz** [comment]
I've opened #39 to fix this. Please try it out when you have the time :)
