### ISSUE TITLE
Why a bindfs rather than a symlink?

### ISSUE THREAD

**Issue by danwdart** [nix-community/impermanence#42]
Just wondered why we bother with bindfs rather than just using a symlink? Wouldn't a bindfs allow blocking until the persistent filesystem is mounted, and wouldn't it not have to wait until half way through the user's session start to be able to be used?

I'm just seeing a lot of things that aren't yet mounted on login even though I should see every mount first, e.g. desktop settings, wifi password keychains etc

**Comment by lovesegfault** [comment]
You mean for the home-manager module or for the NixOS module?

I use the latter extensively and haven't had any similar issues, so I wonder why you're seeing these delayed mounts.

#1 has a long discussion on improving our API to give users more control over how they want state exposed, but work on it has not yet begun.

**Comment by danwdart** [comment]
I mean the home-manager module, but I embed home-manager in the NixOS configuration by importing `"${home-manager}/nixos"` and then `"${impermanence}/home-manager.nix"` if that makes a difference.

Maybe items under `~` would be better managed by `environment.persistence` instead of inside `home.persistence`...

**Comment by talyz** [comment]
The reason for using `bindfs` over symlinks is that some applications don't work well with symlinks and either complain, replace the symlink or just refuse to start. A bind mount is much more transparent to the application, but real bind mounts can't be created by a user, so `bindfs` was chosen instead.

I'm not really sure what problems you're having with the bind mounts. They should be started with your user session as systemd user services. Do you mean that they're not yet started when you've logged in?

**Comment by talyz** [comment]
There were a few applications which didn't work with symlinks - GnuPG is the one I remember right now. There were also issues when you wanted to persist a directory and let home-manager handle some files in it, at least with the way the symlinking was implemented. bindfs should be more transparent to the applications, just like regular bind mounts are.

Sure, it's possible to support both, if necessary. I wasn't aware of any applications which had issues with bindfs and haven't tried using the module with Steam. What errors are you getting?

Going back to your original question, though, what do you mean with things not being mounted on login? The bind mounts are supposed to be set up early on login, before anything else starts in the session. Do they fail completely or do you mean some services start before them and can't access their files?

When using the NixOS module instead of the home-manager one, you would have to specify the whole user folder path for all the files and directories, but otherwise, usage should be the same. Something like this:
```nix
{
  environment.persistence."/persistent/home/talyz" = {
    directories = [
      "/home/talyz/Downloads"
      "/home/talyz/Music"
      "/home/talyz/Pictures"
      "/home/talyz/Documents"
      "/home/talyz/.gnupg"
      "/home/talyz.ssh"
    ];
    files = [
      "/home/talyz/.screenrc"
    ];
  };
}
```

**Comment by nigelgbanks** [comment]
When using NixOS module the bind mounts are created as the root user which creates problems on subsequent writes into those folders if say your mounting into `.config`.

**Comment by talyz** [comment]
I've implemented proper support for users in the NixOS module in #70. This includes solving the permissions issue you mentioned, @nigelgbanks. It also allows for setting default ownership and mode for created directories in general, which is useful for directories used for storing secrets. Help testing it would be appreciated. If it works well enough, I think we could deprecate the `home-manager` module altogether.

**Comment by danwdart** [comment]
@talyz - That sounds really awesome!
@nigelgbanks - I didn't have a problem with permission with the bind/btrfs mounts though, as the directories I was binding in were owned by me already. The only thing I couldn't do was delete the mounted directory (naturally).

**Comment by nigelgbanks** [comment]
I had a bit of an odd use case that I've since abandoned in which my home directory was a `tmpfs` filesystem, but I would bind mount folders like `Downloads` `Projects` and things like `.config/spotify` into the directory from an actual persistent disk. So some of the bind mounts were creating their parent folders. It was too much of a pain to maintain though so I've opt'd to make my home directory the bind mount which is fine.

**Comment by etu** [comment]
> I had a bit of an odd use case that I've since abandoned in which my home directory was a `tmpfs` filesystem, but I would bind mount folders like `Downloads` `Projects` and things like `.config/spotify` into the directory from an actual persistent disk.

You know, this isn't an odd use-case at all. In the rest of the world, it may sound odd. But this project was mainly created around this use-case :wink:
