### ISSUE TITLE
(home-manager) File manager (Nautilus) shows persistent folders as ejectable drives

### ISSUE THREAD

**Issue by Lyndeno** [nix-community/impermanence#64]
Nautilus shows my Documents and Downloads folder as ejectable drive as well as showing drive icons beside them in the file view in /home. A solution I am thinking of would be to allow setting mount options with impermanence so the x-gvfs-hide option can be used.

Unsure whether this option would be set per directory/file or per persistent mount (set mount option that affects all of /nix/persist for example).

**Comment by lovesegfault** [comment]
I think this is fundamentally a bug with Nautilus choosing to display bind mounts like external devices. Should be reported upstream IMO.

**Comment by talyz** [comment]
@lovesegfault I think this refers to the bind mounts created by the `home-manager` module, which are fuse mounts and therefore show up in Nautilus. Regular bind mounts should be [hidden by default](https://gitlab.gnome.org/GNOME/glib/-/issues/2103#note_819048), but could appear anyway in some circumstances (they do to me, probably because bind mounts appear as subvolume mounts on btrfs).

I think we could just always supply the `x-gvfs-hide` option to bind mounts across the board. I don't see any reason why they should ever be shown in Nautilus.
